---
title: "Sales"
author: "StarzsaX"
date: "2024-03-30"
output: html_document
---

```{r}
library(readr) 
library(dplyr)
library(ggplot2)
library(lubridate)
library(plotly)
library(htmlwidgets)
```

```{r}
# Loading the dataset
supermarket_sales_df = read.csv("supermarket_sales.csv", header=T )

# header of he dataset
head(supermarket_sales_df)

```

```{r}
# Checking for any missing values
missing_values <- colSums(is.na(supermarket_sales_df))

print(missing_values)
```

```{r}
# Summary
summary(supermarket_sales_df)

```

```{r}
str(supermarket_sales_df)
```

```{r}
# correcting the format of data types
for(col_num in c(2,3,4,5,6,13)){supermarket_sales_df[,col_num] = as.factor(supermarket_sales_df[,col_num])}
```

```{r}
# Applying date format
supermarket_sales_df$Date <- as.Date(supermarket_sales_df$Date, format="%m/%d/%Y")
```

```{r}
# Adding a binary variable for HighGrossIncome based on the median gross income
supermarket_sales_df <- supermarket_sales_df %>%
  mutate(HighGrossIncome = ifelse(gross.income > median(gross.income), 1, 0))

supermarket_sales_df$HighGrossIncome <- as.factor(supermarket_sales_df$HighGrossIncome)

# Adjusting the time of day to become a factor of 4 levels
supermarket_sales_df$TimeOfDay <- cut(as.integer(substr(supermarket_sales_df$Time, 1, 2)),
                                      breaks = c(-Inf, 6, 12, 18, 24),
                                      labels = c("Night", "Morning", "Afternoon", "Evening"),
                                      right = FALSE)
```

```{r}
# checking format
str(supermarket_sales_df)
```

```{r}

total_sales_by_product <- supermarket_sales_df %>%
  group_by(Product.line) %>%
  summarise(TotalSales = sum(Total))

# Plot of Total Sales by Product Line
ggplot(total_sales_by_product, aes(x = reorder(Product.line, TotalSales), y = TotalSales, fill = Product.line)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = TotalSales), position = position_dodge(width = 0.9), hjust = 1.1, size = 3) + 
  coord_flip() +  # horizontal
  theme_minimal() +
  labs(title = "Total Sales by Product Line", x = "Total Sales", y = "Product Line") +
  theme(legend.position = "bottom", 
        plot.margin = margin(1, 1, 1, 1, "cm"))

```

```{r}
product_performance <- supermarket_sales_df %>%
  group_by(Product.line) %>%
  summarize(AverageRating = mean(Rating), TotalSales = sum(Total))

# Plot of Product Performance: Sales and Ratings
ggplot(product_performance, aes(x = reorder(Product.line, TotalSales), y = TotalSales, fill = AverageRating)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "#F8766D", high = "#00c47f") +
  coord_flip() +
  labs(title = "Product Performance: Sales and Ratings", y = "Product Line", x = "Total Sales")

```

```{r}
customer_sales <- supermarket_sales_df %>% group_by(Customer.type, Gender) %>% summarize(TotalSales = sum(Total))

# Plotting Member Status and Gender
ggplot(customer_sales, aes(x = Customer.type, y = TotalSales, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Sales by Customer Type and Gender", x = "Customer Type", y = "Total Sales")

# Color Theme
# F8766D coral
# 00BFC4 blue

```

```{r}
gender_product_sales <- supermarket_sales_df %>%
  group_by(Product.line, Gender) %>%
  summarize(TotalSales = sum(Total), .groups = 'drop')

# Plot for Sales by Product Line and Gender
ggplot(gender_product_sales, aes(x = Product.line, y = TotalSales, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Sales by Product Line and Gender", x = "Product Line", y = "Total Sales") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate the x-axis text for better readability
```

```{r}
customer_product_sales <- supermarket_sales_df %>%
  group_by(Product.line, Customer.type) %>%
  summarize(TotalSales = sum(Total), .groups = 'drop')

# Plot for Sales by Product Line and Customer Type
ggplot(customer_product_sales, aes(x = Product.line, y = TotalSales, fill = Customer.type)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Sales by Product Line and Customer Type", x = "Product Line", y = "Total Sales") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate the x-axis text for better readability

```

```{r}
# Plotting Member Status and Gender
plot <- ggplot(customer_sales, aes(x = Customer.type, y = TotalSales, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Sales by Customer Type and Gender", x = "Customer Type", y = "Total Sales")

plot

# Extracting fill colors
plot_colors <- ggplot_build(plot)$data[[1]]$fill

# Print the HTML colors
plot_colors

```

```{r}
sales_summary <- supermarket_sales_df %>%
  group_by(Product.line, Gender, Customer.type) %>%
  summarize(TotalSales = sum(Total), .groups = 'drop')

# Plot of Sales by Product Line, Gender and Customer Type
sales_demographics_plot  <- ggplot(sales_summary, aes(x = Product.line, y = TotalSales, fill = Gender, text = paste("Total Sales: ", TotalSales, "<br>Gender: ", Gender, "<br>Member Type: ", Customer.type))) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ Customer.type) + # Separate plots for each Customer Type
  labs(title = "Sales by Product Line, Gender, and Customer Type", 
       x = "Product Line", 
       y = "Total Sales") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
        

# Convert to plotly
plotly_sales_demographics_plot  <- ggplotly(sales_demographics_plot, tooltip = "text")

# bottom legend
plotly_sales_demographics_plot <- plotly_sales_demographics_plot %>%
  layout(
    legend = list(orientation = 'h', x = 0.5, 
                       xanchor = 'center', 
                       y = -0.5, 
                       yanchor = 'top'),
    margin = list(b = 100)
    )


# Plot Visulization
plotly_sales_demographics_plot

```

```{r}
# Pie Chart for City Sales
city_sales <- aggregate(Total ~ City, data = supermarket_sales_df, FUN = sum)
plotly::plot_ly(city_sales, labels = ~City, values = ~Total, type = 'pie', textinfo = 'label+percent',
                insidetextorientation = 'horizontal')

```

```{r}
sales_heatmap_data <- supermarket_sales_df %>%
  group_by(City, Product.line) %>%
  summarize(TotalSales = sum(Total), .groups = 'drop')

# Heat map for Total Sales by City and Product Line
heatmap_plot <- ggplot(sales_heatmap_data, aes(x = City, y = Product.line, fill = TotalSales)) +
  geom_tile() +  # This creates the heatmap tiles
  scale_fill_gradient(low = "#cae2e3", high = "#349094") +  # Adjust color gradient as needed
  labs(title = "Total Sales by City and Product Line", x = "City", y = "Product Line", fill = "Total Sales") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))  # Improve x-axis label readability

# Convert to Plotly for interactivity
plotly_heatmap <- ggplotly(heatmap_plot)

# Display the interactive heatmap
plotly_heatmap

```


```{r}
# This creates a new column for Month
supermarket_sales_df$Month <- format(supermarket_sales_df$Date, "%m")

monthly_sales <- supermarket_sales_df %>% group_by(Month) %>% summarize(TotalSales = sum(Total))
monthly_sales$Month <- factor(monthly_sales$Month,
                               levels = c("01", "02", "03"),
                               labels = c("Jan", "Feb", "Mar"))

# ggplot for Monthly Sales Plot
monthy_sales_p <- ggplot(monthly_sales, aes(x = Month, y = TotalSales, fill = Month)) +
  geom_bar(stat = "identity") +
  scale_x_discrete(labels = c("01" = "Jan", "02" = "Feb", "03" = "Mar")) +
  scale_fill_brewer(palette = "Set2", labels = c("Jan", "Feb", "Mar")) +
  labs(title = "Monthly Sales", x = "Month", y = "Total Sales") +
  theme_minimal()

plotly_monthy_sales <- ggplotly(monthy_sales_p)

plotly_monthy_sales
```

```{r}
sales_by_product_and_month <- supermarket_sales_df %>%
  group_by(Product.line, Month, Day = day(Date)) %>%
  summarize(TotalSales = sum(Total), .groups = 'drop')


# Plot for Daily Sales for Product Line accross Months
DailyAndMonthlySales_plot <- ggplot(sales_by_product_and_month, aes(x = Day, y = TotalSales, color = Month, group = Month)) +
  geom_line(size = 0.7) + 
  geom_point(size = 1) + 
  facet_wrap(~Product.line, scales = "free_y") +
  scale_x_continuous(breaks = seq(1, 31, by = 5)) + 
  #scale_color_manual(values = c("Jan" = "#9B59B6", "Feb" = "#41EAB8", "Mar" = "#E67E22")) + 
  labs(title = "Daily Sales by Product Line Across Months", x = "Day of the Month", y = "Total Sales") +
  theme_minimal() 
 

# Plotly convesion
plotly_DailyAndMonthlySales_plot <- ggplotly(DailyAndMonthlySales_plot)

# JavaScript code
js_code <- "
function(el) {
  var plot = el;
  
  plot.on('plotly_hover', function(data) {
    // Get curve number for the hovered point
    var curveNum = data.points[0].curveNumber;
    // Create an array to reset all line opacities to 0.2
    var update = {
      'opacity': Array(plot.data.length).fill(0.5)
    };
    // Set the opacity of the hovered line to 1 (fully opaque)
    update.opacity[curveNum] = 1;
    
    // Apply the styling
    Plotly.restyle(plot, update);
  })
  .on('plotly_unhover', function(data) {
    // Reset all lines to default opacity
    Plotly.restyle(plot, 'opacity', Array(plot.data.length).fill(0.5));
  });
}
"

# Update legend position to the bottom
plotly_DailyAndMonthlySales_plot <- plotly_DailyAndMonthlySales_plot %>%
  layout(legend = list(orientation = 'h', x = 0.5, xanchor = 'center', y = -0.5, yanchor = 'bottom'))

# Applying JavaScript to plotly plot
plotly_DailyAndMonthlySales_plot <- onRender(plotly_DailyAndMonthlySales_plot, js_code)

plotly_DailyAndMonthlySales_plot

```

```{r}
sales_by_time_product <- supermarket_sales_df %>%
  group_by(Product.line, TimeOfDay) %>%
  summarize(TotalSales = sum(Total), .groups = 'drop')

# Plot of Total Sales by Time of Day for each Product Line
TOD_Prod_plot <- ggplot(sales_by_time_product, aes(x = TimeOfDay, y = TotalSales, fill = TimeOfDay)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~ Product.line, scales = "free_y") +
  labs(title = "Total Sales by Time of Day for Each Product Line", x = "Time of Day", y = "Total Sales") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 40, hjust = 1))

plotly_TOD_Prod_plot <- ggplotly(TOD_Prod_plot)

plotly_TOD_Prod_plot

```

